In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [6]:
# load the dataset
dataset = loadtxt('pima-indians-diabetes.csv', delimiter=',')
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]

In [7]:
X.shape

(768, 8)

In [8]:
y.shape

(768,)

The model expects rows of data with 8 variables (the input_dim=8 argument).<br>
The first hidden layer has 12 nodes and uses the relu activation function.<br>
The second hidden layer has 8 nodes and uses the relu activation function.<br>
The output layer has one node and uses the sigmoid activation function.

In [9]:
# define the keras model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [10]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                108       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [12]:
# fit the keras model on the dataset
model.fit(X, y, epochs=20, batch_size=10)

Epoch 1/20
77/77 [==============================] - 14s 2ms/step - loss: 1.5302 - accuracy: 0.5826
Epoch 2/20
77/77 [==============================] - 0s 2ms/step - loss: 0.9081 - accuracy: 0.6693
Epoch 3/20
77/77 [==============================] - 0s 2ms/step - loss: 0.9085 - accuracy: 0.6530
Epoch 4/20
77/77 [==============================] - 0s 2ms/step - loss: 0.7859 - accuracy: 0.6745
Epoch 5/20
77/77 [==============================] - 0s 2ms/step - loss: 0.7604 - accuracy: 0.6867
Epoch 6/20
77/77 [==============================] - 0s 2ms/step - loss: 0.7278 - accuracy: 0.6628
Epoch 7/20
77/77 [==============================] - 0s 2ms/step - loss: 0.7456 - accuracy: 0.6438
Epoch 8/20
77/77 [==============================] - 0s 2ms/step - loss: 0.6945 - accuracy: 0.6837
Epoch 9/20
77/77 [==============================] - 0s 2ms/step - loss: 0.7408 - accuracy: 0.6504
Epoch 10/20
77/77 [==============================] - 0s 2ms/step - loss: 0.6335 - accuracy: 0.7014
Epoch 11/20
77/77 

In [13]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

24/24 [==============================] - 0s 1ms/step - loss: 0.6360 - accuracy: 0.6771
Accuracy: 67.71


In [15]:
predictions = model.predict_classes(X)

/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [16]:
predictions

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
    

In [17]:
X.shape

(768, 8)

In [20]:
X[0:2]

array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ],
       [  1.   ,  85.   ,  66.   ,  29.   ,   0.   ,  26.6  ,   0.351,
         31.   ]])

In [23]:
y[0:2]

array([1., 0.])

In [24]:
x_new = X[0:2]

In [25]:
y_pred = model.predict(x_new)

In [26]:
y_pred

array([[0.7352886 ],
       [0.10716587]], dtype=float32)

In [29]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [30]:
y == predictions

array([[ True, False,  True, ..., False,  True, False],
       [False,  True, False, ...,  True, False,  True],
       [ True, False,  True, ..., False,  True, False],
       ...,
       [ True, False,  True, ..., False,  True, False],
       [ True, False,  True, ..., False,  True, False],
       [False,  True, False, ...,  True, False,  True]])